// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/urfave/cli"
	"mods/todos/cliapp"
	"mods/todos/conf"
	"mods/todos/models"
)

// Injectors from wire.go:

func initCliApp() (*cli.App, error) {
	appConf := conf.InitCliAppConf()
	dbConf := conf.InitDBConf()
	db := models.InitDB(dbConf)
	app := cliapp.InitCliApp(appConf, db)
	return app, nil
}

func initDb() (*gorm.DB, error) {
	dbConf := conf.InitDBConf()
	db := models.InitDB(dbConf)
	return db, nil
}
