// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/urfave/cli"
	"mods/todos/cliapp"
	"mods/todos/conf"
	"mods/todos/models"
)

// Injectors from wire.go:

func initCliApp() (*cli.App, error) {
	appConf := conf.InitCliAppConf()
	dbConf := conf.InitDBConf()
	db, err := models.InitDB(dbConf)
	if err != nil {
		return nil, err
	}
	app := cliapp.InitCliApp(appConf, db)
	return app, nil
}
